### ISSUE TITLE
Release signing key not obvious to find

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#19]
Problem: see https://github.com/PrivateBin/PrivateBin/issues/352

You just cannot find the release key.

## What to adjust

* [x] Latest release details with "We have switched our key…"
* [x] credits page or so of the website here
* [x] this FAQ part: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-securely-clonedownload-your-project

**Comment by elrido** [comment]
FYI, the key got published to https://privatebin.info/key/release.asc for the release. It is used in at least 3 docker containers for verifying the release.

Instead of a "we changed our key" I would add a section to all signed releases pointing to the key used in that release, since so far we have used three different keys in the last three releases.

I'll update the FAQ, you can handle the release pages. Don't know if one would search for the release key in the credits, though.

**Comment by rugk** [comment]
I am at updating the FAQ… after all, you've assigned me. :smile:

**Comment by rugk** [comment]
Okay, everything done. I did not update the old release notes for older versions, as I do not see a big value in it (after all, users should use the latest fixed version).
If you want to do though, feel free to update it.
